/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harrisonpepese
 */
public class main extends javax.swing.JFrame {
    List<modelo> database;
    List<String> Pcombobox;
    private void update() throws SQLException{
        database = modelo.GetAll();
        Pcombobox = modelo.Getmodel();
    }
    /**
     * Creates new form main
     */
    public main() {
        try {
            update();
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        update_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        inserir_modelo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mInsert = new javax.swing.JButton();
        mlimpar = new javax.swing.JButton();
        Mtipo = new javax.swing.JComboBox<>();
        Mmodelo = new javax.swing.JTextField();
        Mschassi = new javax.swing.JTextField();
        Mcilindrada = new javax.swing.JTextField();
        Mvcusto = new javax.swing.JFormattedTextField();
        Mvvenda = new javax.swing.JFormattedTextField();
        inserir_p = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nmodelo = new javax.swing.JComboBox<>();
        Ncor = new javax.swing.JComboBox<>();
        nquantidade = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Ptipo = new javax.swing.JTextField();
        Pcilindrada = new javax.swing.JTextField();
        Pvcusto = new javax.swing.JTextField();
        Pvvenda = new javax.swing.JTextField();
        Pschassi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Custoproducao = new javax.swing.JTextField();
        Plucro = new javax.swing.JTextField();
        chassiini = new javax.swing.JTextField();
        chassif = new javax.swing.JTextField();
        Pinsert = new javax.swing.JButton();
        Plimpa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pedidos Ronda");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modelo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cilindrada:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("V. Custo:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("V. Venda:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Serie Chassi:");

        mInsert.setText("Inserir");
        mInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mInsertActionPerformed(evt);
            }
        });

        mlimpar.setText("Limpar");
        mlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlimparActionPerformed(evt);
            }
        });

        Mtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo...", "Street", "On/off Road", "Off Road", "Custom", "Naked", "Sport", "Scooter" }));

        Mvcusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        Mvvenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        javax.swing.GroupLayout inserir_modeloLayout = new javax.swing.GroupLayout(inserir_modelo);
        inserir_modelo.setLayout(inserir_modeloLayout);
        inserir_modeloLayout.setHorizontalGroup(
            inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserir_modeloLayout.createSequentialGroup()
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserir_modeloLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(mInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(mlimpar))
                    .addGroup(inserir_modeloLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Mschassi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mtipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mmodelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mvcusto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mcilindrada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mvvenda))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        inserir_modeloLayout.setVerticalGroup(
            inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserir_modeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Mmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Mtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Mcilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Mvcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Mvvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Mschassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_modeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mInsert)
                    .addComponent(mlimpar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inserir Modelo", inserir_modelo);

        jLabel7.setText("Modelo:");

        jLabel8.setText("Cor:");

        jLabel9.setText("quantidade:");

        Nmodelo.setModel(new DefaultComboBoxModel(Pcombobox.toArray()));
        Nmodelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NmodeloItemStateChanged(evt);
            }
        });

        Ncor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Preto", "Cinza", "Vermelho", "Azul", "Amarelo", "Laranja" }));

        nquantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50000, 1));
        nquantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nquantidadeStateChanged(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tipo:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cilindrada:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("V. Custo:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V. Venda:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Serie Chassi:");

        Ptipo.setEditable(false);
        Ptipo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Pcilindrada.setEditable(false);
        Pcilindrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Pvcusto.setEditable(false);
        Pvcusto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Pvvenda.setEditable(false);
        Pvvenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Pschassi.setEditable(false);
        Pschassi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setText("Custo de Producao:");

        jLabel17.setText("Lucro Esperado:");

        jLabel18.setText("Chassi ini.:");

        jLabel19.setText("Chassi final.:");

        Pinsert.setText("Finalizar");
        Pinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinsertActionPerformed(evt);
            }
        });

        Plimpa.setText("Limpar");
        Plimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlimpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inserir_pLayout = new javax.swing.GroupLayout(inserir_p);
        inserir_p.setLayout(inserir_pLayout);
        inserir_pLayout.setHorizontalGroup(
            inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserir_pLayout.createSequentialGroup()
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inserir_pLayout.createSequentialGroup()
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inserir_pLayout.createSequentialGroup()
                                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inserir_pLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ptipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pcilindrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pvcusto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pschassi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pvvenda)))
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Pinsert, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inserir_pLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Nmodelo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(inserir_pLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(Plimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Custoproducao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Plucro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(inserir_pLayout.createSequentialGroup()
                                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19)
                                .addComponent(chassiini, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(chassif))))
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(inserir_pLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inserir_pLayout.createSequentialGroup()
                                .addComponent(Ncor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        inserir_pLayout.setVerticalGroup(
            inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserir_pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ncor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Ptipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Pcilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Pvcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Plucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Custoproducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chassiini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(inserir_pLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Pvvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Pschassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addComponent(chassif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(inserir_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pinsert)
                    .addComponent(Plimpa))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Pedido", inserir_p);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Cor", "Quantidade", "Custo Prod", "Lucro", "Chassi Ini.", "Chassi Fin."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab4", jPanel1);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("RONDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void update_table(){
        DefaultTableModel m=(DefaultTableModel) jTable2.getModel();
        m.setRowCount(0);
        String query="SELECT * FROM `pedido`";
        Connection conn;
        try {
            conn = Conect.GetConection();
            Statement stt= conn.createStatement();
            ResultSet rts=stt.executeQuery(query);
        while(rts.next()){
            m.addRow(new Object[]{rts.getString(1),rts.getString(2),rts.getString(3),rts.getString(4),rts.getString(5),rts.getString(6),rts.getString(7),rts.getString(8)});
        }
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mInsertActionPerformed
        modelo novo = new modelo();
        novo.modelo = Mmodelo.getText();
        novo.tipo = Mtipo.getSelectedItem().toString();
        novo.cilindrada = Integer.parseInt(Mcilindrada.getText());
        novo.V_custo = Double.parseDouble(Mvcusto.getText().replace(".","").replace(",", "."));
        novo.V_venda = Double.parseDouble(Mvvenda.getText().replace(".","").replace(",", "."));
        novo.S_chassi = Mschassi.getText();
        try {
            novo.Insert();
            update();
            Nmodelo.setModel(new DefaultComboBoxModel(Pcombobox.toArray()));
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mInsertActionPerformed

    private void mlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlimparActionPerformed
        
    }//GEN-LAST:event_mlimparActionPerformed

    private void NmodeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NmodeloItemStateChanged
        int i =Pcombobox.indexOf(Nmodelo.getSelectedItem().toString());
        modelo var=database.get(i);
        Pcilindrada.setText(new String(""+var.cilindrada));
        Pschassi.setText(var.S_chassi);
        Ptipo.setText(var.tipo);
        Pvcusto.setText(new String(""+var.V_custo));
        Pvvenda.setText(new String(""+var.V_venda));
                // TODO add your handling code here:
    }//GEN-LAST:event_NmodeloItemStateChanged

    private void nquantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nquantidadeStateChanged
        int i =(Integer)nquantidade.getValue();
        modelo var=database.get(Pcombobox.indexOf(Nmodelo.getSelectedItem().toString()));
        Custoproducao.setText(new String(""+String.format("%.2f", var.V_custo*i)));
        Plucro.setText(new String(""+String.format("%.2f",(var.V_venda-var.V_custo)*i)));
        chassiini.setText(""+var.S_chassi+1);
        chassif.setText(""+var.S_chassi+i);        // TODO add your handling code here:
    }//GEN-LAST:event_nquantidadeStateChanged

    private void PinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinsertActionPerformed
        pedido novo=new pedido();
        novo.modelo=Nmodelo.getSelectedItem().toString();
        novo.cor=Ncor.getSelectedItem().toString();
        novo.quantidade=(Integer)nquantidade.getValue();
        novo.custo=Double.parseDouble(Custoproducao.getText().replace(",","."));
        novo.lucro=Double.parseDouble(Plucro.getText().replace(",","."));
        novo.chassi0=chassiini.getText();
        novo.chassi1=chassif.getText();
        try {
            novo.Insert();
            update_table();
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PinsertActionPerformed

    private void PlimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlimpaActionPerformed

    }//GEN-LAST:event_PlimpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Custoproducao;
    private javax.swing.JTextField Mcilindrada;
    private javax.swing.JTextField Mmodelo;
    private javax.swing.JTextField Mschassi;
    private javax.swing.JComboBox<String> Mtipo;
    private javax.swing.JFormattedTextField Mvcusto;
    private javax.swing.JFormattedTextField Mvvenda;
    private javax.swing.JComboBox<String> Ncor;
    private javax.swing.JComboBox<String> Nmodelo;
    private javax.swing.JTextField Pcilindrada;
    private javax.swing.JButton Pinsert;
    private javax.swing.JButton Plimpa;
    private javax.swing.JTextField Plucro;
    private javax.swing.JTextField Pschassi;
    private javax.swing.JTextField Ptipo;
    private javax.swing.JTextField Pvcusto;
    private javax.swing.JTextField Pvvenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chassif;
    private javax.swing.JTextField chassiini;
    private javax.swing.JPanel inserir_modelo;
    private javax.swing.JPanel inserir_p;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton mInsert;
    private javax.swing.JButton mlimpar;
    private javax.swing.JSpinner nquantidade;
    // End of variables declaration//GEN-END:variables
}
